apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    project: contoso
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: dev
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      limits:
        memory: "100Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: dev
spec:
  selector:
    name: nginx
  ports:
  - port: 80
    targetPort: 80
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: nginx
  namespace: dev
spec:
  podSelector:
    matchLabels:
      name: nginx
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          project: contoso
      podSelector:
        matchLabels:
          name: alpine