apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure
spec:
  storageClassName: azurefile
  resources:
    requests:
      storage: 4Gi
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /mnt/azure
        name: azure
  volumes:
    - name: azure
      persistentVolumeClaim:
        claimName: azure

