apiVersion: v1
kind: Secret
metadata:
  name: azure
type: Opaque
data:
  azurestorageaccountname: <...>
  azurestorageaccountkey: <...>
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /mnt/azure
        name: azure
  volumes:
    - name: azure
      azureFile:
        secretName: azure
        shareName: <...>

